# Logs an update during the execution of a designator.
# - `designator_id`: Unique ID of this designator
# - `json_designator`: Updated JSON (if different from previous log)
# - `timestamp`: Time of update
string designator_id
string json_designator
time stamp
---
bool success
string message
---
string status