# Logs that a designator is now being executed.
# - `designator_id`: Unique ID of this designator
# - `json_designator`: Current JSON content (could be updated)
# - `timestamp`: Time of execution logging
string designator_id
string json_designator
time stamp
---
bool success
string message
---
string status