# Logs that the designator has finished executing.
# - `designator_id`: Unique ID of this designator
# - `json_designator`: Final JSON (if different from last state)
# - `timestamp`: Time of completion
string designator_id
string json_designator
time stamp
---
bool success
string message
---
string status